# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    assets:
        json_manifest_path: ~
        base_urls: ['%env(ASSET_BASE_URL)%']
        packages:
            uploads:
                base_path: ''
                version_strategy: null
                json_manifest_path: ~
                base_urls: ['%env(ASSET_BASE_URL)%']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
