api:
    resource: '../src/Controller/'
    type: attribute
    exclude: 
        - '../src/Controller/RegistrationController.php'
        - '../src/Controller/SecurityController.php'
        - '../src/Controller/DefaultController.php'

authentication:
    resource: '../src/Controller/SecurityController.php'
    type: attribute

registration:
    resource: '../src/Controller/RegistrationController.php'
    type: attribute

app_verify_email:
    path: /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
